export const events = [
  {
    id: 1,
    title: 'Find Your Best Work',
    date: 'Wed, Jan 19',
    time: '1:00 pm - 2:00 PM EST',
    cost: '$10 / Free for members',
    image: require('../assets/Events-Page/Event1.jpg'),
  },
  {
    id: 2,
    title: 'WIN this Fall!',
    date: 'Wed, Jan 26',
    time: '2:00 pm - 5:00 PM EST',
    cost: '$10 / Free for members',
    image: require('../assets/Events-Page/Event2.jpg'),
  },
  {
    id: 3,
    title: 'Collaboratory Info Session',
    date: 'Thurs, Feb 10',
    time: '6:00 pm - 7:00 PM EST',
    cost: 'Free',
    image: require('../assets/Events-Page/Event3.jpg'),
  },
  {
    id: 4,
    title: 'New Member Orientation',
    date: 'Tues, Feb 17',
    time: '2:00 pm - 5:00 PM EST',
    cost: 'Free for new members',
    image: require('../assets/Events-Page/Event4.jpg'),
  },
  {
    id: 1,
    title: 'Find Your Best Work',
    date: 'Wed, Jan 19',
    time: '1:00 pm - 2:00 PM EST',
    cost: '$10 / Free for members',
    image: require('../assets/Events-Page/Event1.jpg'),
  },
  {
    id: 2,
    title: 'WIN this Fall!',
    date: 'Wed, Jan 26',
    time: '2:00 pm - 5:00 PM EST',
    cost: '$10 / Free for members',
    image: require('../assets/Events-Page/Event2.jpg'),
  },
  {
    id: 3,
    title: 'Collaboratory Info Session',
    date: 'Thurs, Feb 10',
    time: '6:00 pm - 7:00 PM EST',
    cost: 'Free',
    image: require('../assets/Events-Page/Event3.jpg'),
  },
  {
    id: 4,
    title: 'New Member Orientation',
    date: 'Tues, Feb 17',
    time: '2:00 pm - 5:00 PM EST',
    cost: 'Free for new members',
    image: require('../assets/Events-Page/Event4.jpg'),
  },
];
